version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: postgres        
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: pochta_russia     
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_go_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: pochta_russia
    ports:
      - "8080:8080"
