version: "3"

tasks:
  run:
    description: "Build and run the application with Docker Compose"
    cmds:
      - sudo docker-compose up --build

  up:
    description: "Initialize the database and start the Go application"
    cmds:
      - psql -U postgres -c "CREATE DATABASE POCHTA_RUSSIA;" || true
      - go run cmd/main/main.go

  down:
    description: "Drop the database"
    cmds:
      - psql -U postgres -c "DROP DATABASE POCHTA_RUSSIA;" || true
